### ISSUE TITLE
"/me gives" is not recognized

### ISSUE THREAD

**Issue by mccoyst** [velour/catbase#16]
Catbase probably sees it in a different form that the IRC weirdo thing. (Or it might not see it at all, given that it seemingly can't send them.)

**Comment by chrissexton** [comment]
An inventory system does not exist right yet, should be a pretty simple addition to write once the other stuff is taken care of. I'd think just some table that tracks item and owner ought to be enough.

**Comment by chrissexton** [comment]
Oh hey, this is a duplicate of #2.
